### ISSUE TITLE
Choice of router

### ISSUE THREAD

**Issue by dukedougal** [gcanti/tcomb-spa-example#4]
I'm curious to know why you chose page instead of react-router.  Are you willing to share your thinking on routers?

thanks!

**Comment by gcanti** [comment]
Oh the reason is trivial: back in the day when I wrote this repo I hadn't experience with RR so I chose page. The pro is that page is a v1.x while RR is (even now) in flux. The major concern is that this app is not "isomorphic". When I will find the time (and RR will hit v1.0) I'll try to replace page with RR and make the code sharable between client and server.

Besides I'm not a big fan of the **current version** of RR:

- it's not truly isomorphic without this patch: git://github.com/bobpace/react-router.git#transitionContext
- defining the router via jsx is weird
- mixing routes definitions with layout (as suggested in its docs) can be misleading, they should be separate concerns
- I'd prefer to define middlewares without using react components

**Comment by gcanti** [comment]
RR 1.0.0 on master
